---
- name: Bind9 installation and configuration
  hosts: dns
  become: True
  tasks:
  - name: Ensure bind9 is installed
    apt: name=bind9

  - name: Configure properly named.conf.local
    copy: >
      src=files/etc/bind/named.conf.local
      dest=/etc/bind/named.conf.local
    notify:
      - restart bind
  - name: Set zone file algonzalvez.com
    copy: >
      src=files/var/cache/bind/db.algonzalvez.com
      dest=/var/cache/bind/db.algonzalvez.com
      mode=644
      owner=bind
      group=bind
    notify:
      - restart bind
  - name: Set zone file 192.168.10.0/24
    copy: >
      src=files/var/cache/bind/db.192.168.10
      dest=/var/cache/bind/db.192.168.10
      mode=644
      owner=bind
      group=bind
    notify:
      - restart bind
      
  handlers:
    - name: restart bind
      service: name=bind9 state=restarted
